# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/location/user
Content-Type: application/json

{"userId":"jane@hotmail.com","coordinates":{"place":{"latitude":37.7534329,"longitude":-122.4344287},"time":1539143909.793000000},"userRole":"DRIVER"}

###
